name: Sync Main
on:
  push:
    branches:
      - develop

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    name: Sync Main Branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Opening update pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "main"
          pr_title: "update: develop to main"
          pr_body: ":crown: *An automated Pull Request to keep main updated.*"
          pr_label: "auto-update"
          github_token: ${{ secrets.GITHUB_TOKEN }}
